# Data Exploration

In [1]:
import pandas as pd

## 1. Import a csv file to DataFrame

In [3]:
url = "https://drive.google.com/file/d/1MHjM8PtzvqIqwSwnoCh_Y803txx6BfNt/view?usp=drive_link" # orderlines.csv
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orderlines_df = pd.read_csv(path)

## 2. DataFrame dimensions using the "DataFrame.shape" attribute

To calculate the dimensions (number of rows and columns) of the DataFrame.

In [4]:
orderlines_df

,id,id_order,product_id,product_quantity,sku,unit_price,date
0,1119109,299539,0,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,0,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,0,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,0,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,0,1,JBL0104,23.74,2017-01-01 01:06:38
...,...,...,...,...,...,...,...
293978,1650199,527398,0,1,JBL0122,42.99,2018-03-14 13:57:25
293979,1650200,527399,0,1,PAC0653,141.58,2018-03-14 13:57:34
293980,1650201,527400,0,2,APP0698,9.99,2018-03-14 13:57:41
293981,1650202,527388,0,1,BEZ0204,19.99,2018-03-14 13:58:01
293982,1650203,527401,0,1,APP0927,13.99,2018-03-14 13:58:36

In [ ]:
orderlines_df.shape

(293983, 7)

In [ ]:
# Printing number of rows and columns

nrows = orderlines_df.shape[0]
ncols = orderlines_df.shape[1]
print("The number of rows is", nrows)
print("The number of columns is", ncols)

The number of rows is 293983
The number of columns is 7

In [ ]:
# Data size
orderlines_df.size

2057881

Checking if the `.size` and `.shape` agree

In [ ]:
orderlines_df.shape[0] * orderlines_df.shape[1] == orderlines_df.size

True

Calculating the number of dimensions that the DataFrame has.

In [ ]:
orderlines_df.ndim

2

## 3. DataFrames exploration

In [ ]:
orderlines_df.head()

,id,id_order,product_id,product_quantity,sku,unit_price,date
0,1119109,299539,0,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,0,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,0,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,0,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,0,1,JBL0104,23.74,2017-01-01 01:06:38

In [ ]:
orderlines_df.head(15)

,id,id_order,product_id,product_quantity,sku,unit_price,date
0,1119109,299539,0,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,0,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,0,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,0,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,0,1,JBL0104,23.74,2017-01-01 01:06:38
5,1119114,295310,0,10,WDT0249,231.79,2017-01-01 01:14:27
6,1119115,299544,0,1,APP1582,1.137.99,2017-01-01 01:17:21
7,1119116,299545,0,1,OWC0100,47.49,2017-01-01 01:46:16
8,1119119,299546,0,1,IOT0014,18.99,2017-01-01 01:50:34
9,1119120,295347,0,1,APP0700,72.19,2017-01-01 01:54:11
10,1119125,299548,0,5,SPE0132,35.14,2017-01-01 02:02:20
11,1119126,299549,0,1,PAC0929,2.565.99,2017-01-01 02:07:42
12,1119127,299550,0,1,WDT0309,149.14,2017-01-01 02:09:52
13,1119129,299552,0,1,MBI0010,16.99,2017-01-01 02:13:51
14,1119130,299552,0,1,SAT0044,19.99,2017-01-01 02:14:36

In [ ]:
orderlines_df.tail(9)

,id,id_order,product_id,product_quantity,sku,unit_price,date
293974,1650194,527395,0,1,MMW0030,20.99,2018-03-14 13:55:22
293975,1650195,527396,0,1,PAC0653,141.58,2018-03-14 13:55:44
293976,1650196,527384,0,1,LAC0227,249.99,2018-03-14 13:56:02
293977,1650198,527397,0,1,JBL0122,42.99,2018-03-14 13:56:38
293978,1650199,527398,0,1,JBL0122,42.99,2018-03-14 13:57:25
293979,1650200,527399,0,1,PAC0653,141.58,2018-03-14 13:57:34
293980,1650201,527400,0,2,APP0698,9.99,2018-03-14 13:57:41
293981,1650202,527388,0,1,BEZ0204,19.99,2018-03-14 13:58:01
293982,1650203,527401,0,1,APP0927,13.99,2018-03-14 13:58:36

## 4. Checking for missing values, duplicates, descriptive stats, exploring data types and overall counts of columns & rows

In [ ]:
# exploring data types

orderlines_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293983 entries, 0 to 293982
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                293983 non-null  int64
 1   id_order          293983 non-null  int64
 2   product_id        293983 non-null  int64
 3   product_quantity  293983 non-null  int64
 4   sku               293983 non-null  object
 5   unit_price        293983 non-null  object
 6   date              293983 non-null  object
dtypes: int64(4), object(3)
memory usage: 15.7+ MB

In [ ]:
# Overview of descriptive stats for the numerical columns

orderlines_df.describe()

                 id       id_order  product_id  product_quantity
count  2.939830e+05  293983.000000    293983.0     293983.000000
mean   1.397918e+06  419999.116544         0.0          1.121126
std    1.530096e+05   66344.486479         0.0          3.396569
min    1.119109e+06  241319.000000         0.0          1.000000
25%    1.262542e+06  362258.500000         0.0          1.000000
50%    1.406940e+06  425956.000000         0.0          1.000000
75%    1.531322e+06  478657.000000         0.0          1.000000
max    1.650203e+06  527401.000000         0.0        999.000000

In [ ]:
# Counts

orderlines_df.nunique()

id                  293983
id_order            204855
product_id               1
product_quantity        67
sku                   7951
unit_price           11329
date                251631
dtype: int64

In [ ]:
# Column unique value counts

sorted(orderlines_df["product_quantity"].unique())#[:10]

[np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19),
 np.int64(20),
 np.int64(21),
 np.int64(22),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(27),
 np.int64(28),
 np.int64(29),
 np.int64(30),
 np.int64(31),
 np.int64(32),
 np.int64(33),
 np.int64(34),
 np.int64(35),
 np.int64(36),
 np.int64(37),
 np.int64(39),
 np.int64(41),
 np.int64(46),
 np.int64(47),
 np.int64(50),
 np.int64(51),
 np.int64(54),
 np.int64(55),
 np.int64(57),
 np.int64(60),
 np.int64(66),
 np.int64(69),
 np.int64(70),
 np.int64(72),
 np.int64(80),
 np.int64(89),
 np.int64(92),
 np.int64(97),
 np.int64(98),
 np.int64(99),
 np.int64(100),
 np.int64(125),
 np.int64(126),
 np.int64(164),
 np.int64(192),
 np.int64(200),
 np.int64(201),
 np.int64(555),
 np.int64(800),
 np.int64(999)]

In [ ]:
#Checking for missing values

orderlines_df.isna()

,id,id_order,product_id,product_quantity,sku,unit_price,date
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
293978,False,False,False,False,False,False,False
293979,False,False,False,False,False,False,False
293980,False,False,False,False,False,False,False
293981,False,False,False,False,False,False,False
293982,False,False,False,False,False,False,False

In [ ]:
orderlines_df.isna().sum()

id                  0
id_order            0
product_id          0
product_quantity    0
sku                 0
unit_price          0
date                0
dtype: int64

In [ ]:
# Checking for duplicates

orderlines_df.duplicated().sum()

np.int64(0)

# 5. Checking rows with the largest & smallest value

In [ ]:
#Largest value

orderlines_df.nlargest(5, "product_quantity")

,id,id_order,product_id,product_quantity,sku,unit_price,date
53860,1228150,346221,0,999,APP1190,55.99,2017-04-14 21:50:52
68712,1254032,358747,0,999,SEV0028,19.99,2017-05-24 14:51:58
57796,1234924,349475,0,800,KIN0137,7.49,2017-04-25 09:59:00
57306,1234111,349133,0,555,APP0665,70.99,2017-04-24 10:20:13
40813,1204788,335057,0,201,THU0029,80.99,2017-03-14 15:25:53

In [ ]:
#Smallest value

orderlines_df.nsmallest(5, "product_quantity")

,id,id_order,product_id,product_quantity,sku,unit_price,date
0,1119109,299539,0,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,0,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,0,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,0,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,0,1,JBL0104,23.74,2017-01-01 01:06:38

In [ ]:
#Check columns with product quantities > 100

orderlines_df.loc[orderlines_df["product_quantity"] > 100]

# orderlines_df.query("product_quantity > 100")

,id,id_order,product_id,product_quantity,sku,unit_price,date
27779,1180010,323959,0,126,ADN0039,34.99,2017-02-14 10:21:12
40813,1204788,335057,0,201,THU0029,80.99,2017-03-14 15:25:53
53860,1228150,346221,0,999,APP1190,55.99,2017-04-14 21:50:52
57306,1234111,349133,0,555,APP0665,70.99,2017-04-24 10:20:13
57796,1234924,349475,0,800,KIN0137,7.49,2017-04-25 09:59:00
68712,1254032,358747,0,999,SEV0028,19.99,2017-05-24 14:51:58
136675,1388261,417536,0,200,TRK0009,29.99,2017-10-25 15:02:39
204637,1500715,464858,0,192,APP1662,519.00,2017-12-17 15:53:04
246048,1574262,496172,0,164,EVU0013,19.99,2018-01-22 16:14:42
285492,1637611,522075,0,125,XDO0047,25.99,2018-03-06 10:07:54

In [ ]:
# Importing orders.csv DataFrame

url = "https://drive.google.com/file/d/18c-Z5VBy2hcUlnjnvfpqAHFhzMR1e36e/view?usp=drive_link" # orders.csv
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orders_df = pd.read_csv(path)

In [ ]:
# merging orders_df and orderlines_df

orders_df.merge(orderlines_df, right_on="id_order", left_on="order_id").query("total_paid > 600")

,order_id,created_date,total_paid,state,id,id_order,product_id,product_quantity,sku,unit_price,date
26,251969,2017-11-21 21:04:12,610.07,Completed,1419094,251969,0,1,APP2150,590.08,2017-11-21 19:40:12
28,253220,2017-10-04 19:37:10,1610.00,Completed,1369930,253220,0,2,LGE0044,559.99,2017-10-04 19:15:16
29,253220,2017-10-04 19:37:10,1610.00,Completed,1369933,253220,0,1,ELA0010,61.74,2017-10-04 19:19:07
30,253220,2017-10-04 19:37:10,1610.00,Completed,1369936,253220,0,1,APP1465,99.99,2017-10-04 19:20:57
31,253220,2017-10-04 19:37:10,1610.00,Completed,1369937,253220,0,1,APP1214,82.99,2017-10-04 19:21:14
...,...,...,...,...,...,...,...,...,...,...,...
293651,527314,2018-03-14 13:07:56,799.99,Place Order,1650032,527314,0,1,APP2477,793.00,2018-03-14 13:07:56
293661,527321,2018-03-14 13:16:30,3503.99,Pending,1650045,527321,0,1,PAC2148,3.497.00,2018-03-14 13:10:15
293663,527324,2018-03-14 13:10:56,3075.00,Shopping Basket,1650050,527324,0,1,PAC2117,3.075.00,2018-03-14 13:10:56
293683,527342,2018-03-14 13:24:51,1335.99,Place Order,1650088,527342,0,1,APP2492,1.329.00,2018-03-14 13:24:51
293706,527364,2018-03-14 13:36:13,1329.00,Shopping Basket,1650135,527364,0,1,APP2491,1.329.00,2018-03-14 13:36:13