# Searching for the category

For this code along we are only going to use the products DataFrame. However, if you believe there is information in other tables that can help to create categories, please feel free to explore.

In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import matplotlib.ticker as ticker

In [4]:
# products_cl.csv
url = "https://drive.google.com/file/d/1hNIdQvyGLdqgpm1zwe-OeCXpMK36waOC/view?usp=drive_link"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
products_cl = pd.read_csv(path)


# orderlines.csv
url = "https://drive.google.com/file/d/1HN97kzfr6BDZqAUH0VfjniTO7VIjsQ-4/view?usp=drive_link"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orderlines_cl = pd.read_csv(path)

In [5]:
# products_cl.csv
url = "https://drive.google.com/file/d/1hNIdQvyGLdqgpm1zwe-OeCXpMK36waOC/view?usp=drive_link"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
products_cl = pd.read_csv(path)

product_category_df = products_cl.copy()

In [6]:
# orderlines.csv
url = "https://drive.google.com/file/d/1HN97kzfr6BDZqAUH0VfjniTO7VIjsQ-4/view?usp=drive_link"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orderlines_cl = pd.read_csv(path)

## Using `type` to create categories

In [7]:
category_type_df = products_cl.copy()

In [8]:
category_type_df.head()

,sku,name,desc,price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,0,1387
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,0,1230
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,1,1364

Here are the `type`s that have the most products.

In [9]:
category_type_df.groupby("type").count().nlargest(52, "sku")

            sku  name  desc  price  in_stock
type
11865403   1057  1057  1057   1057      1057
12175397    939   939   939    939       939
1298        783   783   783    783       783
11935397    562   562   562    562       562
11905404    454   454   454    454       454
1282        373   373   373    373       373
12635403    362   362   362    362       362
13835403    269   269   269    269       269
5,74E+15    247   247   247    247       247
1364        216   216   216    216       216
12585395    190   190   190    190       190
1296        187   187   187    187       187
1325        183   183   183    183       183
5384        178   178   178    178       178
1433        171   171   171    171       171
12215397    170   170   170    170       170
5398        159   159   159    159       159
1,02E+12    130   130   130    130       130
1,44E+11    129   129   129    129       129
57445397    129   129   129    129       129
1334        115   115   115    115       115
2158        107   107   107    107       107
2449        107   107   107    107       107
12655397    105   105   105    105       105
1229        104   104   104    104       104
12995397     95    95    95     95        95
1515         85    85    85     85        85
13615399     78    78    78     78        78
13555403     75    75    75     75        75
1405         75    75    75     75        75
1230         73    73    73     73        73
118692158    72    72    72     72        72
1216         67    67    67     67        67
24885185     67    67    67     67        67
24895185     67    67    67     67        67
21485407     66    66    66     66        66
1392         65    65    65     65        65
11821715     58    58    58     58        58
8696         57    57    57     57        57
9094         50    50    50     50        50
5,39E+11     47    47    47     47        47
5,49E+11     45    45    45     45        45
42945397     44    44    44     44        44
12645406     43    43    43     43        43
51601716     43    43    43     43        43
2,16E+11     42    42    42     42        42
85651716     42    42    42     42        42
24215399     41    41    41     41        41
5720         40    40    40     40        40
14305406     39    39    39     39        39
5405         39    39    39     39        39
13005399     37    37    37     37        37

Checking `type` to see if we can make categories from this column.

In [12]:
category_type_df.loc[category_type_df["type"] == "13005399"].sample(5)

,sku,name,desc,price,in_stock,type
5726,LMP0023,"LMP battery MacBook Pro 17 ""Unibody Early / Mi...",replacement battery compatible with MacBook Pr...,129.99,1,13005399
7191,AP20135,Like new - Apple 85W MagSafe 2 charger MacBook...,Power charger reacondicioando MagSafe 2 of 85 ...,89.00,0,13005399
2140,APP0701,Apple 45W MagSafe 2 charger MacBook Air in Ju...,Apple charger MacBook Air MagSafe 2 45W withou...,89.00,1,13005399
1539,MOB0013,Mobee Magic Feet Charger Apple Wireless Keyboa...,Charger for Apple Wireless Keyboard and Magic ...,149.90,0,13005399
627,APP0703,"85W MagSafe charger Apple MacBook Pro 15 ""/ 17...",Apple MagSafe Power Charger 85W MacBook Pro un...,89.00,1,13005399

In [ ]:
# Categories for the project

# ------

# category_type_df.groupby("type").count().nlargest(52, "sku")

# ------

category_type_df.loc[category_type_df["type"] == "11865403"].sample(10) ## Type 1: iPhone Case
category_type_df.loc[category_type_df["type"] == "12175397"].sample(10) ## Type 2: Networking/NAS
category_type_df.loc[category_type_df["type"] == "1298"].sample(10) ## Type 3: A MESS. Everything is there (possibly goes to other/unclassified)
category_type_df.loc[category_type_df["type"] == "11935397"].sample(10) ## Type 4: Hard Drives
category_type_df.loc[category_type_df["type"] == "11905404"].sample(10) ## Type 5: Smart Watches and Accessories
category_type_df.loc[category_type_df["type"] == "1282"].sample(10) ## Type 6: Apple Mac computers
category_type_df.loc[category_type_df["type"] == "12635403"].sample(10) ## Type 7: iPad Cases
category_type_df.loc[category_type_df["type"] == "13835403"].sample(10) ## Type 8: Mac Cases
category_type_df.loc[category_type_df["type"] == "5,74E+15"].sample(10) ## Type 9: iMac desktop computers
category_type_df.loc[category_type_df["type"] == "1364"].sample(10) ## Type 10: RAM/Memory
category_type_df.loc[category_type_df["type"] == "12585395"].sample(10) ## Type 11: Adapter & Cables
category_type_df.loc[category_type_df["type"] == "1296"].sample(10) ## Type 12: Monitors
category_type_df.loc[category_type_df["type"] == "1325"].sample(10) ## Type 13: Cables & Adapters
category_type_df.loc[category_type_df["type"] == "5384"].sample(10) ## Type 14: Headphones
category_type_df.loc[category_type_df["type"] == "1433"].sample(10) ## Type 15: Hard Drives extensions
category_type_df.loc[category_type_df["type"] == "12215397"].sample(10) ## Type 16: Hard Drive extensions
category_type_df.loc[category_type_df["type"] == "5398"].sample(10) ## Type 17: Wireless Speakers
category_type_df.loc[category_type_df["type"] == "1,02E+12"].sample(10) ## Type 18: New Macbooks
category_type_df.loc[category_type_df["type"] == "1,44E+11"].sample(10) ## Type 19: Repair Service + parts
category_type_df.loc[category_type_df["type"] == "57445397"].sample(10) ## Type 20: SD cards + Pendrives
category_type_df.loc[category_type_df["type"] == "1334"].sample(10) ## Type 21: Networking (routers etc)
category_type_df.loc[category_type_df["type"] == "2158"].sample(10) ## Type 22: New MacBooks
category_type_df.loc[category_type_df["type"] == "2449"].sample(10) ## Type 23: Watch Straps
category_type_df.loc[category_type_df["type"] == "12655397"].sample(10) ## Type 24: Hard drives
category_type_df.loc[category_type_df["type"] == "1229"].sample(10) ## Type 25: Pens & Pointers
category_type_df.loc[category_type_df["type"] == "12995397"].sample(10) ## Type 26: Docking Stations
category_type_df.loc[category_type_df["type"] == "1515"].sample(10) ## Type 27: External Bateries
category_type_df.loc[category_type_df["type"] == "13615399"].sample(10) ## Type 28: Chargers & Docking station with chargeing
category_type_df.loc[category_type_df["type"] == "13555403"].sample(10) ## Type 29: Screen Protector
category_type_df.loc[category_type_df["type"] == "1405"].sample(10) ## Type 30: Graphic Tablets
category_type_df.loc[category_type_df["type"] == "1230"].sample(10) ## Type 31: Adapters, Cable extensions etc.
category_type_df.loc[category_type_df["type"] == "118692158"].sample(10) ## Type 32: Apple iMac Pro 27 (huge prices)
category_type_df.loc[category_type_df["type"] == "1216"].sample(10) ## Type 33: Adjustable Stands
category_type_df.loc[category_type_df["type"] == "24885185"].sample(10) ## Type 34: Apple Watch 38mm
category_type_df.loc[category_type_df["type"] == "24895185"].sample(10) ## Type 35: Apple Watch 40mm
category_type_df.loc[category_type_df["type"] == "21485407"].sample(10) ## Type 36: Repair parts for old iPhones
category_type_df.loc[category_type_df["type"] == "1392"].sample(10) ## Type 37: Backpacks, Case/Carriage accessories
category_type_df.loc[category_type_df["type"] == "11821715"].sample(10) ## Type 38: iPods
category_type_df.loc[category_type_df["type"] == "8696"].sample(10) ## Type 39: Computer Stands
category_type_df.loc[category_type_df["type"] == "9094"].sample(10) ## Type 40: Surveillance Cameras
category_type_df.loc[category_type_df["type"] == "5,39E+11"].sample(10) ## Type 41: New Macbooks
category_type_df.loc[category_type_df["type"] == "5,49E+11"].sample(10) ## Type 42: iPhone Battery Cases
category_type_df.loc[category_type_df["type"] == "42945397"].sample(10) ## Type 43: Pendrives & external storages
category_type_df.loc[category_type_df["type"] == "12645406"].sample(10) ## Type 44: Repair Parts (mostly old devices)
category_type_df.loc[category_type_df["type"] == "51601716"].sample(10) ## Type 45: Refurbished Phones (iphone 5, 6 mostly)
category_type_df.loc[category_type_df["type"] == "2,16E+11"].sample(10) ## Type 46: Apple iMacs 21.5"
category_type_df.loc[category_type_df["type"] == "85651716"].sample(10) ## Type 47: Refurbished Phones  (iphone 7s mostly)
category_type_df.loc[category_type_df["type"] == "24215399"].sample(10) ## Type 48: Docking & Charging for watches
category_type_df.loc[category_type_df["type"] == "5720"].sample(10) ## Type 49: Stands for phones
category_type_df.loc[category_type_df["type"] == "14305406"].sample(10) ## Type 50: Repair tools
category_type_df.loc[category_type_df["type"] == "5405"].sample(10) ## Type 51: Arm bands, straps for Phones (sport activities)
category_type_df.loc[category_type_df["type"] == "13005399"].sample(10) ## Type 52: Power banks & chargers

In [ ]:
# Number of product types

category_type_df.groupby("type").count().nlargest(52, "sku")

            sku  name  desc  price  in_stock
type
11865403   1057  1057  1057   1057      1057
12175397    939   939   939    939       939
1298        783   783   783    783       783
11935397    562   562   562    562       562
11905404    454   454   454    454       454
1282        373   373   373    373       373
12635403    362   362   362    362       362
13835403    269   269   269    269       269
5,74E+15    247   247   247    247       247
1364        216   216   216    216       216
12585395    190   190   190    190       190
1296        187   187   187    187       187
1325        183   183   183    183       183
5384        178   178   178    178       178
1433        171   171   171    171       171
12215397    170   170   170    170       170
5398        159   159   159    159       159
1,02E+12    130   130   130    130       130
1,44E+11    129   129   129    129       129
57445397    129   129   129    129       129
1334        115   115   115    115       115
2158        107   107   107    107       107
2449        107   107   107    107       107
12655397    105   105   105    105       105
1229        104   104   104    104       104
12995397     95    95    95     95        95
1515         85    85    85     85        85
13615399     78    78    78     78        78
13555403     75    75    75     75        75
1405         75    75    75     75        75
1230         73    73    73     73        73
118692158    72    72    72     72        72
1216         67    67    67     67        67
24885185     67    67    67     67        67
24895185     67    67    67     67        67
21485407     66    66    66     66        66
1392         65    65    65     65        65
11821715     58    58    58     58        58
8696         57    57    57     57        57
9094         50    50    50     50        50
5,39E+11     47    47    47     47        47
5,49E+11     45    45    45     45        45
42945397     44    44    44     44        44
12645406     43    43    43     43        43
51601716     43    43    43     43        43
2,16E+11     42    42    42     42        42
85651716     42    42    42     42        42
24215399     41    41    41     41        41
5720         40    40    40     40        40
14305406     39    39    39     39        39
5405         39    39    39     39        39
13005399     37    37    37     37        37

#Type to category

In [13]:
#

type_to_category = {
    # 1. Apple Computers & Desktops
    "1282":       "Apple Computers & Desktops",  # Type 6
    "5,74E+15":   "Apple Computers & Desktops",  # Type 9
    "1,02E+12":   "Apple Computers & Desktops",  # Type 18
    "2158":       "Apple Computers & Desktops",  # Type 22
    "118692158":  "Apple Computers & Desktops",  # Type 32
    "5,39E+11":   "Apple Computers & Desktops",  # Type 41
    "2,16E+11":   "Apple Computers & Desktops",  # Type 46

    # 2. Apple Mobile Devices
    "11821715":   "Apple Mobile Devices",        # Type 38 iPods
    "51601716":   "Apple Mobile Devices",        # Type 45
    "85651716":   "Apple Mobile Devices",        # Type 47

    # 3. Apple Wearables & Accessories
    "11905404":   "Apple Wearables & Accessories", # Type 5
    "2449":       "Apple Wearables & Accessories", # Type 23
    "24885185":   "Apple Wearables & Accessories", # Type 34
    "24895185":   "Apple Wearables & Accessories", # Type 35
    "24215399":   "Apple Wearables & Accessories", # Type 48

    # 4. Cases & Screen Protection
    "11865403":   "Cases & Screen Protection",   # Type 1
    "12635403":   "Cases & Screen Protection",   # Type 7
    "13835403":   "Cases & Screen Protection",   # Type 8
    "13555403":   "Cases & Screen Protection",   # Type 29
    "5,49E+11":   "Cases & Screen Protection",   # Type 42

    # 5. Storage & Memory
    "11935397":   "Storage & Memory",            # Type 4
    "1364":       "Storage & Memory",            # Type 10
    "1433":       "Storage & Memory",            # Type 15
    "12215397":   "Storage & Memory",            # Type 16
    "57445397":   "Storage & Memory",            # Type 20
    "12655397":   "Storage & Memory",            # Type 24
    "42945397":   "Storage & Memory",            # Type 43

    # 6. Cables, Adapters & Networking
    "12175397":   "Cables, Adapters & Networking", # Type 2
    "12585395":   "Cables, Adapters & Networking", # Type 11
    "1325":       "Cables, Adapters & Networking", # Type 13
    "1334":       "Cables, Adapters & Networking", # Type 21
    "12995397":   "Cables, Adapters & Networking", # Type 26
    "1405":       "Cables, Adapters & Networking", # Type 30
    "1230":       "Cables, Adapters & Networking", # Type 31

    # 7. Audio, Peripherals & Accessories
    "1296":       "Audio, Peripherals & Accessories", # Type 12 - Monitors
    "5384":       "Audio, Peripherals & Accessories", # Type 14 - Headphones
    "5398":       "Audio, Peripherals & Accessories", # Type 17 - Wireless Speakers
    "1229":       "Audio, Peripherals & Accessories", # Type 25 - Pens & Pointers
    "1515":       "Audio, Peripherals & Accessories", # Type 27 - External Batteries
    "13615399":   "Audio, Peripherals & Accessories", # Type 28 - Chargers & Docking
    "1216":       "Audio, Peripherals & Accessories", # Type 33 - Adjustable Stands
    "1392":       "Audio, Peripherals & Accessories", # Type 37 - Backpacks & Carry
    "8696":       "Audio, Peripherals & Accessories", # Type 39 - Computer Stands
    "9094":       "Audio, Peripherals & Accessories", # Type 40 - Surveillance Cameras
    "5720":       "Audio, Peripherals & Accessories", # Type 49 - Phone Stands
    "5405":       "Audio, Peripherals & Accessories", # Type 51 - Armbands & Straps
    "13005399":   "Audio, Peripherals & Accessories", # Type 52 - Power Banks & Chargers

    # 8. Repair & Maintenance
    "1,44E+11":   "Repair & Maintenance",        # Type 19
    "21485407":   "Repair & Maintenance",        # Type 36
    "12645406":   "Repair & Maintenance",        # Type 44
    "14305406":   "Repair & Maintenance",        # Type 50

    # 9. Open Items / Resale
    "1298":       "Open Items / Resale",         # Type 3
}

# Apply the mapping, unmatched types fall into "Others"
category_type_df["category"] = category_type_df["type"].map(type_to_category).fillna("Others")

#Clasification by type:

 * Top 9 types = 50% of products (50% would have to be considered as "Others')
 * Top 14 types = 60% of products (40% would have to be considered as "Others")
 * Top 21 types = 70% of products (30% would have to be considered as "Others")
 * Top 32 types = 80% of products (20% would have to be considered as "Others")
 * Top 52 types = 90% of products (10% would have to be considered as "Others")

# List of categories in Eniac's Datasets

- Apple Computers & Desktops (Types 6, 9, 18, 22, 32, 41, 46) iMacs, MacBooks (new & refurbished), iMac Pro
- Apple Mobile Devices (Types 38, 45, 47), ipods, iPhones (refurbished)
- Apple Wearables & Accessories (Types 5, 23, 34, 35, 48) Apple Watches, watch straps, docking/charging for watches
- Cases & Screen Protection (Types 1, 7, 8, 29, 42) iPhone cases, iPad cases, Mac cases, screen protectors, battery cases
- Storage & Memory (Types 4, 10, 15, 16, 20, 24, 43) Hard drives, RAM, SD cards, pendrives, external storage
- Cables, Adapters & Networking (Types 2, 11, 13, 21, 26, 30, 31) Networking/NAS, cables, adapters, routers, docking stations
- Audio, Peripherals & Accessories (Types 12, 14, 17, 25, 27, 28, 33, 37, 39, 40, 49, 51, 52) Monitors, headphones, wireless speakers, pens & pointers, power banks, chargers, stands, backpacks, iPods, surveillance cameras, phone stands, armbands
- Repair & Maintenance (Types 19, 36, 44, 50) Repair parts, repair services, repair tools
- Open Items / Resale (Type 3) Open box & resale items
- Others Remaining ~10% of products not covered by the 52 types

In [16]:
# Grouping and condensing the categories into recognisable items

category_type_df.value_counts("category")

category
Cases & Screen Protection           1808
Cables, Adapters & Networking       1670
Storage & Memory                    1397
Audio, Peripherals & Accessories    1146
Apple Computers & Desktops          1018
Others                              1014
Open Items / Resale                  783
Apple Wearables & Accessories        736
Repair & Maintenance                 277
Apple Mobile Devices                 143
Name: count, dtype: int64

#  Adding the categories to the DataFrame

In [17]:
# Adding the categories to the DataFrame


category_type_df = category_type_df.merge(
    category_type_df[['type', 'category']],
    on='type',
    how='left'
)

category_type_df.head()

,sku,name,desc,price,in_stock,type,category_x,category_y
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696,"Audio, Peripherals & Accessories","Audio, Peripherals & Accessories"
1,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696,"Audio, Peripherals & Accessories","Audio, Peripherals & Accessories"
2,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696,"Audio, Peripherals & Accessories","Audio, Peripherals & Accessories"
3,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696,"Audio, Peripherals & Accessories","Audio, Peripherals & Accessories"
4,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696,"Audio, Peripherals & Accessories","Audio, Peripherals & Accessories"

In [ ]:
category_type_df.loc[category_type_df["category_x"] == "Others"].describe()

              price      in_stock
count  23396.000000  23396.000000
mean     804.059840      0.200718
std     1317.273673      0.400546
min        4.900000      0.000000
25%       55.990000      0.000000
50%      489.000000      0.000000
75%      899.000000      0.000000
max     8249.000000      1.000000

In [ ]:
category_type_df.loc[category_type_df["category_x"] == "Apple Mobile Devices"].describe()

             price     in_stock
count  6977.000000  6977.000000
mean    465.243373     0.057331
std     316.937225     0.232491
min      29.950000     0.000000
25%     229.000000     0.000000
50%     409.000000     0.000000
75%     779.000000     0.000000
max    1130.330000     1.000000

In [ ]:
category_type_df.loc[category_type_df["category"] == "Apple Computers & Desktops"].describe()

              price     in_stock
count   1018.000000  1018.000000
mean    3371.985570     0.026523
std     2381.921435     0.160762
min      309.990000     0.000000
25%     1949.000000     0.000000
50%     2739.000000     0.000000
75%     3685.590000     0.000000
max    15339.000000     1.000000

# Expanding the orderlines table -  orderlines_expanded

In [27]:
# Merging orderlines_cl and category_type_df

orderlines_expanded = orderlines_cl.merge(category_type_df, on="sku", how="right")
orderlines_expanded

,id,id_order,product_id,product_quantity,sku,unit_price,date,unit_price_total,revenue,name,desc,price,in_stock,type,category_x,category_y
0,1121326.0,300551.0,0.0,1.0,RAI0007,54.99,2017-01-02 13:34:30,54.99,54.99,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696,"Audio, Peripherals & Accessories","Audio, Peripherals & Accessories"
1,1149253.0,310820.0,0.0,1.0,RAI0007,49.99,2017-01-17 09:37:43,49.99,49.99,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696,"Audio, Peripherals & Accessories","Audio, Peripherals & Accessories"
2,1149773.0,311042.0,0.0,1.0,RAI0007,49.99,2017-01-17 15:55:39,49.99,49.99,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696,"Audio, Peripherals & Accessories","Audio, Peripherals & Accessories"
3,1181573.0,324568.0,0.0,1.0,RAI0007,54.99,2017-02-15 13:36:16,54.99,54.99,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696,"Audio, Peripherals & Accessories","Audio, Peripherals & Accessories"
4,1188189.0,327565.0,0.0,1.0,RAI0007,54.99,2017-02-22 13:01:25,54.99,54.99,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696,"Audio, Peripherals & Accessories","Audio, Peripherals & Accessories"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17192952,NaN,NaN,NaN,NaN,THU0063,NaN,NaN,NaN,NaN,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,1,1392,"Audio, Peripherals & Accessories","Audio, Peripherals & Accessories"
17192953,NaN,NaN,NaN,NaN,THU0063,NaN,NaN,NaN,NaN,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,1,1392,"Audio, Peripherals & Accessories","Audio, Peripherals & Accessories"
17192954,NaN,NaN,NaN,NaN,THU0063,NaN,NaN,NaN,NaN,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,1,1392,"Audio, Peripherals & Accessories","Audio, Peripherals & Accessories"
17192955,NaN,NaN,NaN,NaN,THU0063,NaN,NaN,NaN,NaN,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,1,1392,"Audio, Peripherals & Accessories","Audio, Peripherals & Accessories"
17192956,NaN,NaN,NaN,NaN,THU0063,NaN,NaN,NaN,NaN,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,1,1392,"Audio, Peripherals & Accessories","Audio, Peripherals & Accessories"